#!/usr/bin/env bash
#
# 02-ssh-hardening.sh - SSH server hardening
#
# Hardens SSH configuration with security best practices
# This script is run LAST to avoid lockout during installation
#

set -euo pipefail

# Colors
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly NC='\033[0m'

log_info() { echo -e "${GREEN}[SSH]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[SSH]${NC} $*"; }
log_error() { echo -e "${RED}[SSH]${NC} $*"; }

# Configuration
SSH_PORT="${SSH_PORT:-22}"
DISABLE_ROOT_LOGIN="${DISABLE_ROOT_LOGIN:-no}"
ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"

# ============================================================================
# BACKUP
# ============================================================================

backup_ssh_config() {
    log_info "Backing up SSH configuration..."

    local backup_dir="/root/server-setup-backup/ssh"
    mkdir -p "$backup_dir"

    local timestamp
    timestamp=$(date +%Y%m%d-%H%M%S)

    cp /etc/ssh/sshd_config "${backup_dir}/sshd_config.${timestamp}"
    cp -r /etc/ssh/sshd_config.d "${backup_dir}/sshd_config.d.${timestamp}" 2>/dev/null || true

    log_info "Backup saved to: $backup_dir"
}

# ============================================================================
# SSH HARDENING
# ============================================================================

configure_ssh_hardening() {
    log_info "Applying SSH hardening configuration..."

    local config_file="/etc/ssh/sshd_config"
    local custom_config="/etc/ssh/sshd_config.d/99-hardening.conf"

    # Create custom config directory if it doesn't exist
    mkdir -p /etc/ssh/sshd_config.d

    # Create hardened configuration
    cat > "$custom_config" << 'EOF'
# SSH Hardening Configuration
# Generated by Secure Server Setup Framework

# Network
Port SSH_PORT_PLACEHOLDER
AddressFamily any
ListenAddress 0.0.0.0
ListenAddress ::

# Authentication
PermitRootLogin PERMIT_ROOT_PLACEHOLDER
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
KbdInteractiveAuthentication no
UsePAM yes

# Crypto
# Use strong ciphers only
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

# Use strong MACs only
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256

# Use strong key exchange algorithms
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256

# Use strong host key algorithms
HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com

# Security settings
X11Forwarding no
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
PermitUserEnvironment no
AllowAgentForwarding no
AllowTcpForwarding no
PermitTunnel no
DebianBanner no

# Limits
MaxAuthTries 3
MaxSessions 2
LoginGraceTime 30
ClientAliveInterval 300
ClientAliveCountMax 2

# Logging
SyslogFacility AUTH
LogLevel VERBOSE

# Allow specific users only (will be updated by user creation script)
# AllowUsers ADMIN_USERNAME_PLACEHOLDER
EOF

    # Replace placeholders
    sed -i "s/SSH_PORT_PLACEHOLDER/${SSH_PORT}/g" "$custom_config"
    sed -i "s/ADMIN_USERNAME_PLACEHOLDER/${ADMIN_USERNAME}/g" "$custom_config"

    if [[ "$DISABLE_ROOT_LOGIN" == "yes" ]]; then
        sed -i "s/PERMIT_ROOT_PLACEHOLDER/no/g" "$custom_config"
    else
        sed -i "s/PERMIT_ROOT_PLACEHOLDER/prohibit-password/g" "$custom_config"
    fi

    log_info "SSH hardening configuration created"
}

configure_ssh_banner() {
    log_info "Configuring SSH banner..."

    cat > /etc/ssh/banner << 'EOF'
╔═══════════════════════════════════════════════════════════════════════╗
║                       AUTHORIZED ACCESS ONLY                          ║
╚═══════════════════════════════════════════════════════════════════════╝

This system is for authorized use only. All activity is monitored and
logged. Unauthorized access attempts will be prosecuted to the full
extent of applicable laws.

EOF

    # Enable banner in SSH config
    if ! grep -q "^Banner /etc/ssh/banner" /etc/ssh/sshd_config.d/99-hardening.conf 2>/dev/null; then
        echo "Banner /etc/ssh/banner" >> /etc/ssh/sshd_config.d/99-hardening.conf
    fi

    log_info "SSH banner configured"
}

generate_ed25519_host_key() {
    log_info "Ensuring Ed25519 host key exists..."

    if [[ ! -f /etc/ssh/ssh_host_ed25519_key ]]; then
        ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N "" -q
        log_info "Generated Ed25519 host key"
    else
        log_info "Ed25519 host key already exists"
    fi
}

disable_weak_host_keys() {
    log_info "Disabling weak host keys..."

    # Backup and remove DSA and ECDSA keys (keep RSA and Ed25519)
    local keys_to_remove=(
        "/etc/ssh/ssh_host_dsa_key"
        "/etc/ssh/ssh_host_dsa_key.pub"
    )

    for key in "${keys_to_remove[@]}"; do
        if [[ -f "$key" ]]; then
            mv "$key" "${key}.disabled"
            log_info "Disabled: $(basename "$key")"
        fi
    done
}

configure_ssh_client() {
    log_info "Hardening SSH client configuration..."

    local ssh_config="/etc/ssh/ssh_config.d/99-hardening.conf"
    mkdir -p /etc/ssh/ssh_config.d

    cat > "$ssh_config" << 'EOF'
# SSH Client Hardening Configuration

Host *
    # Use strong ciphers
    Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com

    # Use strong MACs
    MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com

    # Use strong key exchange
    KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512

    # Prefer Ed25519 keys
    HostKeyAlgorithms ssh-ed25519,rsa-sha2-512,rsa-sha2-256

    # Security
    HashKnownHosts yes
    StrictHostKeyChecking ask
    VerifyHostKeyDNS yes
EOF

    log_info "SSH client configuration hardened"
}

test_ssh_config() {
    log_info "Testing SSH configuration..."

    if ! sshd -t; then
        log_error "SSH configuration test failed!"
        return 1
    fi

    log_info "SSH configuration is valid"
    return 0
}

update_firewall_for_ssh() {
    log_info "Updating firewall rules for SSH port ${SSH_PORT}..."

    # If UFW is installed and active
    if command -v ufw &> /dev/null; then
        if ufw status | grep -q "Status: active"; then
            # Allow new SSH port before applying changes
            ufw allow "${SSH_PORT}/tcp" comment "SSH" || true

            # If changing from default port, remove old rule after new one works
            if [[ "$SSH_PORT" != "22" ]]; then
                log_warn "Remember to test SSH on port ${SSH_PORT} before removing port 22"
            fi
        fi
    fi

    log_info "Firewall updated for SSH"
}

restart_ssh_safely() {
    log_warn "═══════════════════════════════════════════════════════"
    log_warn "  IMPORTANT: About to restart SSH service"
    log_warn "═══════════════════════════════════════════════════════"
    log_warn ""
    log_warn "SSH will restart with new configuration:"
    log_warn "  Port: ${SSH_PORT}"
    log_warn "  Root login: $([ "$DISABLE_ROOT_LOGIN" == "yes" ] && echo "DISABLED" || echo "ENABLED")"
    log_warn "  Password auth: DISABLED"
    log_warn ""
    log_warn "Make sure you have:"
    log_warn "  1. SSH key properly configured for ${ADMIN_USERNAME}"
    log_warn "  2. Another terminal open to test connection"
    log_warn "  3. Console access via your hosting provider"
    log_warn ""

    # In non-interactive mode, wait a bit for user to read
    if [[ "${NON_INTERACTIVE:-false}" == "true" ]]; then
        sleep 3
    else
        read -p "Press Enter to restart SSH (Ctrl+C to abort)..." -r
    fi

    log_info "Restarting SSH service..."

    if systemctl restart ssh || systemctl restart sshd; then
        log_info "SSH service restarted successfully"

        # Wait for SSH to be ready
        sleep 2

        if systemctl is-active --quiet ssh || systemctl is-active --quiet sshd; then
            log_info "SSH service is running"
        else
            log_error "SSH service failed to start!"
            return 1
        fi
    else
        log_error "Failed to restart SSH service!"
        return 1
    fi

    return 0
}

create_ssh_test_script() {
    log_info "Creating SSH test script..."

    cat > /root/test-ssh.sh << 'EOF'
#!/bin/bash
#
# Test SSH connection with new configuration
#

SSH_PORT="${SSH_PORT:-22}"
ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"

echo "Testing SSH connection..."
echo "Port: $SSH_PORT"
echo "User: $ADMIN_USERNAME"
echo ""
echo "From another terminal, run:"
echo "  ssh -p $SSH_PORT $ADMIN_USERNAME@$(hostname -I | awk '{print $1}')"
echo ""
echo "If you can connect successfully, close this terminal."
echo "If not, you may need console access to fix the configuration."
EOF

    chmod +x /root/test-ssh.sh

    log_info "Test script created: /root/test-ssh.sh"
}

show_connection_info() {
    local server_ip
    server_ip=$(hostname -I | awk '{print $1}')

    echo ""
    log_info "═══════════════════════════════════════════════════════"
    log_info "  SSH CONFIGURATION COMPLETE"
    log_info "═══════════════════════════════════════════════════════"
    echo ""
    log_info "SSH is now hardened with the following settings:"
    echo ""
    echo "  Port: ${SSH_PORT}"
    echo "  Root Login: $([ "$DISABLE_ROOT_LOGIN" == "yes" ] && echo "Disabled" || echo "Key-only")"
    echo "  Password Auth: Disabled"
    echo "  Admin User: ${ADMIN_USERNAME}"
    echo ""
    log_warn "⚠️  TEST YOUR SSH CONNECTION NOW!"
    echo ""
    echo "In a NEW terminal window, connect with:"
    echo ""
    echo "  ssh -p ${SSH_PORT} ${ADMIN_USERNAME}@${server_ip}"
    echo ""
    echo "Or if root is still allowed:"
    echo ""
    echo "  ssh -p ${SSH_PORT} root@${server_ip}"
    echo ""
    log_warn "Do NOT close this terminal until you verify the connection works!"
    echo ""
    log_info "═══════════════════════════════════════════════════════"
    echo ""
}

# ============================================================================
# MAIN
# ============================================================================

main() {
    log_info "Starting SSH hardening..."
    echo ""

    # Backup existing configuration
    backup_ssh_config

    # Apply hardening
    generate_ed25519_host_key
    disable_weak_host_keys
    configure_ssh_hardening
    configure_ssh_banner
    configure_ssh_client

    # Test configuration
    if ! test_ssh_config; then
        log_error "SSH configuration is invalid! Rolling back..."
        # Restore from backup
        local latest_backup
        latest_backup=$(ls -t /root/server-setup-backup/ssh/sshd_config.* | head -1)
        if [[ -f "$latest_backup" ]]; then
            cp "$latest_backup" /etc/ssh/sshd_config
            log_info "Configuration restored from backup"
        fi
        return 1
    fi

    # Update firewall
    update_firewall_for_ssh

    # Create test script
    create_ssh_test_script

    # Restart SSH service
    if ! restart_ssh_safely; then
        log_error "SSH restart failed!"
        return 1
    fi

    # Show connection information
    show_connection_info

    log_info "SSH hardening complete!"
    return 0
}

main "$@"
